### PR TITLE
Port to Gtk+3 and update sugargame

### PR DESCRIPTION
**Pull request by yell0wfl4sh**
@quozl  please review!

### CODE REVIEW

**Comment by chimosky** [comment]
@yashagrawal3 activity display doesn't show properly, activity is zoomed in and doesn't get to the edge of screen.

**Comment by yell0wfl4sh** [comment]
@chimosky  That wasn't introduced in due to my changes, that can be fixed in another issue.

**Comment by chimosky** [comment]
@yashagrawal3 see if you can fix the issue first before porting.

**Comment by quozl** [comment]
Thanks.  Reviewed to f19de9a.  Noted https://github.com/sugarlabs/ayni-activity/issues/3 but don't really understand the problem "zoomed in".  Is it that the activity was written for a fixed display size of 1200x900 and needs to support any size?

**Comment by yell0wfl4sh** [comment]
@quozl yes! @chimosky said to do so, but I think it can be handled separately.

**Comment by chimosky** [comment]
@quozl yes.

**Comment by quozl** [comment]
Thanks.  Merging.  No reason not to.  As far as I'm concerned, issue #3 can be fixed any time, no need to hold up GTK+ 3 port just for it.  What your mentors tell you is up to them.  :grin:

**Pull request merged**
